rootLogger.level = ERROR
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = console

appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %msg%n

logger.spark.name = org.apache.spark
logger.spark.level = ERROR

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = ERROR

logger.jetty.name = org.eclipse.jetty
logger.jetty.level = ERROR

logger.py4j.name = py4j
logger.py4j.level = ERROR